apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: fillit
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: fillit  # Deployment의 Pod 라벨
  podMetricsEndpoints:
    - path: /actuator/prometheus
      port: "metrics"   # Spring Boot의 메트릭 엔드포인트가 열려 있는 포트
      interval: 15s
