apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: fillit
  namespace: default  # fillit 애플리케이션과 동일한 네임스페이스로 변경
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: fillit
  podMetricsEndpoints:
    - port: metrics
      path: /actuator/prometheus
      interval: 15s
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_host_ip]
          regex: (.*)
          targetLabel: __address__
          replacement: '$1:8090'
