apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fillit-ingress
  annotations:
    # cert-manager가 ClusterIssuer를 사용하여 인증서를 발급하도록 지정
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # Nginx Ingress Controller 사용
    kubernetes.io/ingress.class: "nginx"
    # HTTP로 접속 시 HTTPS로 강제 리다이렉트
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - fillit.kro.kr
      # cert-manager가 발급한 인증서와 키가 저장될 Secret 이름
      secretName: fillit-tls-qpr6s
  rules:
    - host: fillit.kro.kr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fillit-service
                port:
                  number: 8080
