stages:
  - build
  - deploy

build:
  stage: build
  image: node:16
  script:
    - cd fillit_frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - fillit_frontend/dist

deploy:
  stage: deploy
  image: node:16
  script:
    - npm install -g vercel
    - vercel --token $VERCEL_TOKEN --prod --confirm
  only:
    - dev_front
